import { liveIp } from '../config/IpAddress';
const coopIp = liveIp + 'coop/';

export const crateItemGroupUrl = liveIp + 'inventory/create-item-group';
export const getItemGroupUrl = liveIp + 'inventory/all-items-groups';
export const updateItemGroupUrl = liveIp + 'inventory/update-item-group';
export const createMeasurementUnitUrl = liveIp + 'inventory/create-measurement-unit';
export const updateMeasurementUnitUrl = liveIp + 'inventory/update-measurement-unit';
export const getMeasurementUnitUrl = liveIp + 'inventory/all-measurement-unit';
export const createItemCategoryUrl = liveIp + 'inventory/create-item-category';
export const updateItemCategoryUrl = liveIp + 'inventory/update-item-category';
export const getItemCategoryUrl = liveIp + 'inventory/all-item-category';
export const getAllDoptorUrl = liveIp + 'inventory/all-doptors';
export const createItemUrl = liveIp + 'inventory/create-item';
export const getItemUrl = liveIp + 'inventory/get-all-item';
export const updateItemUrl = liveIp + 'inventory/update-item';
export const codeMasterTypesUrl = liveIp + 'master/data/codeMaster?codeType=';
export const doptorLayerUrl = liveIp + 'master/data/officeLayer';
export const officeUrl = liveIp + 'master/data/officeList/inventory';
export const employeeDesignationUrl = liveIp + 'master/data/employeeRecord/inventory';

export const officeUnitUrl = liveIp + 'master/data/unit-list';
export const storeGetUrl = liveIp + 'inventory/get-store';
export const storeCreateUrl = liveIp + 'inventory/create-store';
export const storeUpdateUrl = liveIp + 'inventory/update-store';
export const supplierCreateUrl = liveIp + 'inventory/supplier-create';
export const supplierUpdateUrl = liveIp + 'inventory/supplier-update';
export const supplierGetUrl = liveIp + 'inventory/get-supplier';
export const allotmentInfoUrl = liveIp + 'inventory/allotment-info/';
export const officeOriginUrl = liveIp + 'inventory/office-origin';
export const officeUnitsUrl = liveIp + 'inventory/all-office-unit';
export const upsertAllotmentUrl = liveIp + 'inventory/insert-update-allotment';
export const getItemsForExcelUrl = liveIp + 'inventory/get-item-for-excel';
export const getItemRequistionPurposeUrl = liveIp + 'inventory/requisition-purpose';
export const doptorWiseOfficeListUrl = liveIp + 'master/data/childOfficeList';
export const serviceNameUrl = liveIp + 'service-info';
export const doptorItemInfoUrl = liveIp + 'inventory/doptor-item/';
export const returnableItemListUrl = liveIp + 'inventory/returnable-items';
export const nonFixedReturnableItemsUrl = liveIp + 'inventory/non-fixed-returnable-items';
export const isStoreAdminUrl = liveIp + 'inventory/isStoreAdmin';
export const storeAdminInfoUrl = liveIp + 'inventory/get-store-admin-info';
